### ISSUE TITLE
'err : ALSR is None'

### ISSUE THREAD

**Issue by idewindy** [yangyss/lldb-trace#4]
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
  File "/Users/incollagepro/lldb-trace/lldbTrace.py", line 409, in print_tracing_progress
    file_addr = mem_addr - ASLR 

还有589  也是NoneType 需要加上 str(sym_name)
self.append_msg = sym_name + self.append_msg

**Comment by yangyss** [comment]
this cause by init_ASLR() fun。
befroe   code  ”print('err : ALSR is None') “  add "ASLR = '' "

at line 589:
    value's type had been checked by  parser_ins_symbol_name()  fun。

**Comment by idewindy** [comment]
我是对一个系统方法打的断点，然后解析出现的问题，ASLR 不应该会为空啊
