### ISSUE TITLE
遇到了一个报错

### ISSUE THREAD

**Issue by ChandHsu** [yangyss/lldb-trace#6]
error: libarclite_iphoneos.a(arclite.o) failed to load objfile for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a                   │
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.                                                                                                                 │
Stack dump:                                                                                                                                                                                           │
0.      Program arguments: /Applications/Xcode.app/Contents/Developer/usr/bin/lldb
是什么原因呢？

**Comment by zacard-orc** [comment]
+1 同问
